language: go
sudo: required
go:
  - 1.4.3
  - 1.5.4
  - 1.6.2
install:
  - go get -d -v -t ./...
script:
  - export GOMAXPROCS=$(nproc)
  - go test ./...
  - go build -o tg ./cli/cli.go
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "tg"
#  skip_cleanup: true
#  on:
#    tags: true